// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Action struct {
	Period    string   `json:"period"`
	Task      string   `json:"task"`
	Details   string   `json:"details"`
	Timeline  string   `json:"timeline"`
	Resources []string `json:"resources"`
}

type ActionPlan struct {
	ShortTerm []Action `json:"shortTerm"`
	MidTerm   []Action `json:"midTerm"`
	LongTerm  []Action `json:"longTerm"`
}

type AllPathsResp struct {
	Code           int             `json:"code"`
	Msg            string          `json:"msg"`
	PromotionPaths []PromotionPath `json:"promotionPaths"`
	TransferPaths  []TransferPath  `json:"transferPaths"`
}

type CareerPath struct {
	TargetJob     JobNode     `json:"targetJob"`
	IndustryTrend string      `json:"industryTrend"`
	SocialDemand  string      `json:"socialDemand"`
	Milestones    []Milestone `json:"milestones"`
}

type CareerReport struct {
	Id            int64          `json:"id"`
	StudentId     int64          `json:"studentId"`
	Title         string         `json:"title"`
	Overview      ReportOverview `json:"overview"`
	MatchAnalysis MatchAnalysis  `json:"matchAnalysis"`
	CareerPath    CareerPath     `json:"careerPath"`
	ActionPlan    ActionPlan     `json:"actionPlan"`
	Content       string         `json:"content"`
	Status        string         `json:"status"`
	CreatedAt     int64          `json:"createdAt"`
	UpdatedAt     int64          `json:"updatedAt"`
}

type CreateJobReq struct {
	Name         string       `json:"name,optional" validate:"omitempty,min=2,max=100"`
	Description  string       `json:"description,optional" validate:"omitempty,max=2000"`
	Company      string       `json:"company,optional" validate:"omitempty,max=200"`
	Industry     string       `json:"industry,optional" validate:"omitempty,max=100"`
	Location     string       `json:"location,optional" validate:"omitempty,max=200"`
	SalaryRange  string       `json:"salaryRange,optional" validate:"omitempty,max=100"`
	Skills       []Skill      `json:"skills,optional"`
	Certificates []string     `json:"certificates,optional"`
	SoftSkills   SoftSkills   `json:"softSkills,optional"`
	Requirements Requirements `json:"requirements,optional"`
}

type CreateStudentReq struct {
	Name           string         `json:"name,optional" validate:"omitempty,min=2,max=50"`
	Education      string         `json:"education,optional" validate:"omitempty,oneof=high_school bachelor master phd"`
	Major          string         `json:"major,optional" validate:"omitempty,min=2,max=100"`
	GraduationYear int            `json:"graduationYear,optional" validate:"omitempty,min=2020,max=2030"`
	Skills         []StudentSkill `json:"skills,optional"`
	Certificates   []StudentCert  `json:"certificates,optional"`
	SoftSkills     SoftSkills     `json:"softSkills,optional"`
	Internship     []Internship   `json:"internship,optional"`
	Projects       []Project      `json:"projects,optional"`
}

type ErrorResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type ExportReq struct {
	ReportId int64  `json:"reportId" validate:"required,gt=0"`
	Format   string `json:"format" validate:"required,oneof=pdf docx json"`
}

type ExportResp struct {
	Code    int    `json:"code"`
	Msg     string `json:"msg"`
	Url     string `json:"url"`
	Content string `json:"content,optional"`
}

type Gap struct {
	Attribute  string  `json:"attribute"`
	Required   int     `json:"required"`
	Current    int     `json:"current"`
	GapPercent float64 `json:"gapPercent"`
	Suggestion string  `json:"suggestion"`
}

type GenerateProfileReq struct {
	ResumeContent string `json:"resumeContent" validate:"required,min=10"`
}

type GenerateReportReq struct {
	StudentId   int64         `json:"studentId" validate:"required,gt=0"`
	TargetJobId int64         `json:"targetJobId,optional" validate:"omitempty,gt=0"`
	Options     ReportOptions `json:"options,optional"`
}

type GenerateReportStreamReq struct {
	StudentId   int64  `json:"studentId" validate:"required,gt=0"`
	Track       string `json:"track" validate:"required,oneof=full quick gap"`
	TargetJobId int64  `json:"targetJobId,optional" validate:"omitempty,gt=0"`
}

type HealthResp struct {
	Status  string `json:"status"`
	Version string `json:"version"`
}

type Internship struct {
	Company     string `json:"company"`
	Position    string `json:"position"`
	Duration    int    `json:"duration"`
	Description string `json:"description"`
}

type JobGenerateReq struct {
	PositionName string `json:"positionName" validate:"required,min=2,max=50"`
	Industry     string `json:"industry,optional" validate:"omitempty,max=100"`
	RawData      string `json:"rawData,optional" validate:"omitempty,max=5000"`
}

type JobGraphReq struct {
	JobId int64 `path:"id"`
}

type JobListReq struct {
	Page     int    `form:"page,default=1 validate:"omitempty,min=1"`
	PageSize int    `form:"pageSize,default=10 validate:"omitempty,min=1,max=100"`
	Industry string `form:"industry,optional"`
	Name     string `form:"name,optional"`
}

type JobListResp struct {
	Total int64        `json:"total"`
	List  []JobProfile `json:"list"`
}

type JobListResultResp struct {
	Code int          `json:"code"`
	Msg  string       `json:"msg"`
	Data *JobListResp `json:"data,optional"`
}

type JobNode struct {
	Id          int64    `json:"id"`
	Name        string   `json:"name"`
	Level       int      `json:"level"`
	Description string   `json:"description"`
	Skills      []string `json:"skills"`
}

type JobProfile struct {
	Id              int64        `json:"id"`
	Name            string       `json:"name"`
	Description     string       `json:"description"`
	Company         string       `json:"company"`
	Industry        string       `json:"industry"`
	Location        string       `json:"location"`
	SalaryRange     string       `json:"salaryRange"`
	Skills          []Skill      `json:"skills"`
	Certificates    []string     `json:"certificates"`
	SoftSkills      SoftSkills   `json:"softSkills"`
	GrowthPotential string       `json:"growthPotential"`
	Requirements    Requirements `json:"requirements"`
	CreatedAt       int64        `json:"createdAt"`
	UpdatedAt       int64        `json:"updatedAt"`
}

type JobRef struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type JobResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data *JobProfile `json:"data,optional"`
}

type LoginReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	Token   string `json:"token"`
	Expires int64  `json:"expires"`
	UserId  int64  `json:"userId"`
}

type MatchAnalysis struct {
	OverallScore float64       `json:"overallScore"`
	Strengths    []string      `json:"strengths"`
	Weaknesses   []string      `json:"weaknesses"`
	TopMatches   []MatchResult `json:"topMatches"`
}

type MatchListReq struct {
	StudentId int64   `json:"studentId" validate:"required,gt=0"`
	Page      int     `form:"page,default=1 validate:"omitempty,min=1"`
	PageSize  int     `form:"pageSize,default=10 validate:"omitempty,min=1,max=100"`
	MinScore  float64 `form:"minScore,optional validate:"omitempty,min=0,max=100"`
	Industry  string  `form:"industry,optional validate:"omitempty,max=100"`
}

type MatchListResp struct {
	Code  int           `json:"code"`
	Msg   string        `json:"msg"`
	Total int64         `json:"total"`
	List  []MatchResult `json:"list"`
}

type MatchReq struct {
	StudentId int64 `json:"studentId" validate:"required,gt=0"`
	JobId     int64 `json:"jobId" validate:"required,gt=0"`
}

type MatchResult struct {
	JobId           int64   `json:"jobId"`
	JobName         string  `json:"jobName"`
	OverallScore    float64 `json:"overallScore"`
	SkillsMatch     float64 `json:"skillsMatch"`
	CertsMatch      float64 `json:"certsMatch"`
	SoftSkillsMatch float64 `json:"softSkillsMatch"`
	ExperienceMatch float64 `json:"experienceMatch"`
	GapAnalysis     []Gap   `json:"gapAnalysis"`
}

type MatchResultResp struct {
	Code int          `json:"code"`
	Msg  string       `json:"msg"`
	Data *MatchResult `json:"data,optional"`
}

type MatchScoreResp struct {
	Code  int     `json:"code"`
	Msg   string  `json:"msg"`
	Score float64 `json:"score"`
}

type Milestone struct {
	Stage    string   `json:"stage"`
	Year     int      `json:"year"`
	Position string   `json:"position"`
	Skills   []string `json:"skills"`
	Salary   string   `json:"salary"`
}

type PolishReq struct {
	ReportId int64  `json:"reportId" validate:"required,gt=0"`
	Level    string `json:"level" validate:"required,oneof=light normal thorough"`
}

type Project struct {
	Name         string   `json:"name"`
	Role         string   `json:"role"`
	Description  string   `json:"description"`
	Technologies []string `json:"technologies"`
}

type PromotionPath struct {
	JobId    int64     `json:"jobId"`
	JobName  string    `json:"jobName"`
	NextJobs []JobNode `json:"nextJobs"`
}

type PromotionPathResp struct {
	Code int            `json:"code"`
	Msg  string         `json:"msg"`
	Data *PromotionPath `json:"data,optional"`
}

type RegisterReq struct {
	Username string `json:"username" validate:"required,min=3,max=20"`
	Password string `json:"password" validate:"required,min=6,max=20"`
	Email    string `json:"email" validate:"required,email"`
	Phone    string `json:"phone,optional" validate:"omitempty,len=11"`
}

type RelatedJobsReq struct {
	JobId int64  `path:"id"`
	Type  string `path:"type,options=[promotion transfer related]"`
}

type ReportListReq struct {
	Page      int    `form:"page,default=1 validate:"omitempty,min=1"`
	PageSize  int    `form:"pageSize,default=10 validate:"omitempty,min=1,max=100"`
	StudentId int64  `form:"studentId,optional validate:"omitempty,gt=0"`
	Status    string `form:"status,optional validate:"omitempty,oneof=draft completed failed"`
}

type ReportListResp struct {
	Total int64          `json:"total"`
	List  []CareerReport `json:"list"`
}

type ReportListResultResp struct {
	Code int             `json:"code"`
	Msg  string          `json:"msg"`
	Data *ReportListResp `json:"data,optional"`
}

type ReportOptions struct {
	IncludeGapAnalysis bool `json:"includeGapAnalysis"`
	IncludeActionPlan  bool `json:"includeActionPlan"`
	DetailedLevel      int  `json:"detailedLevel" validate:"omitempty,min=1,max=3"`
}

type ReportOverview struct {
	StudentName     string   `json:"studentName"`
	Education       string   `json:"education"`
	Major           string   `json:"major"`
	Completeness    float64  `json:"completeness"`
	Competitiveness float64  `json:"competitiveness"`
	TopJobs         []JobRef `json:"topJobs"`
}

type ReportResp struct {
	Code int           `json:"code"`
	Msg  string        `json:"msg"`
	Data *CareerReport `json:"data,optional"`
}

type Requirements struct {
	Education  string `json:"education"`
	Experience string `json:"experience"`
	Internship string `json:"internship"`
}

type ResumeUploadReq struct {
	FileContent string `json:"fileContent" validate:"required"`
	FileName    string `json:"fileName" validate:"required,min=1,max=255"`
}

type Skill struct {
	Name     string `json:"name"`
	Level    int    `json:"level"`
	Required bool   `json:"required"`
}

type SoftSkills struct {
	Innovation    int `json:"innovation"`
	Learning      int `json:"learning"`
	Pressure      int `json:"pressure"`
	Communication int `json:"communication"`
	Teamwork      int `json:"teamwork"`
}

type StudentCert struct {
	Name  string `json:"name"`
	Level string `json:"level"`
	Year  int    `json:"year"`
}

type StudentListReq struct {
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"pageSize,default=10"`
	Major     string `form:"major,optional"`
	Education string `form:"education,optional"`
}

type StudentListResp struct {
	Total int64            `json:"total"`
	List  []StudentProfile `json:"list"`
}

type StudentListResultResp struct {
	Code int              `json:"code"`
	Msg  string           `json:"msg"`
	Data *StudentListResp `json:"data,optional"`
}

type StudentProfile struct {
	Id              int64          `json:"id"`
	UserId          int64          `json:"userId"`
	Name            string         `json:"name"`
	Education       string         `json:"education"`
	Major           string         `json:"major"`
	GraduationYear  int            `json:"graduationYear"`
	Skills          []StudentSkill `json:"skills"`
	Certificates    []StudentCert  `json:"certificates"`
	SoftSkills      SoftSkills     `json:"softSkills"`
	Internship      []Internship   `json:"internship"`
	Projects        []Project      `json:"projects"`
	Completeness    float64        `json:"completeness"`
	Competitiveness float64        `json:"competitiveness"`
	CreatedAt       int64          `json:"createdAt"`
	UpdatedAt       int64          `json:"updatedAt"`
}

type StudentResp struct {
	Code int             `json:"code"`
	Msg  string          `json:"msg"`
	Data *StudentProfile `json:"data,optional"`
}

type StudentSkill struct {
	Name  string `json:"name"`
	Level int    `json:"level"`
	Years int    `json:"years"`
}

type TransferPath struct {
	FromJob        JobNode  `json:"fromJob"`
	ToJob          JobNode  `json:"toJob"`
	MatchScore     float64  `json:"matchScore"`
	TransferSkills []string `json:"transferSkills"`
	LearningPath   []string `json:"learningPath"`
}

type TransferPathsResp struct {
	Code int            `json:"code"`
	Msg  string         `json:"msg"`
	Data []TransferPath `json:"data,optional"`
}

type UpdateJobReq struct {
	Id           int64        `json:"id" validate:"required,gt=0"`
	Name         string       `json:"name,optional" validate:"omitempty,min=2,max=100"`
	Description  string       `json:"description,optional" validate:"omitempty,max=2000"`
	Company      string       `json:"company,optional" validate:"omitempty,max=200"`
	Industry     string       `json:"industry,optional" validate:"omitempty,max=100"`
	Location     string       `json:"location,optional" validate:"omitempty,max=200"`
	SalaryRange  string       `json:"salaryRange,optional" validate:"omitempty,max=100"`
	Skills       []Skill      `json:"skills,optional"`
	Certificates []string     `json:"certificates,optional"`
	SoftSkills   SoftSkills   `json:"softSkills,optional"`
	Requirements Requirements `json:"requirements,optional"`
}

type UpdateReportReq struct {
	Id      int64  `json:"id" validate:"required,gt=0"`
	Title   string `json:"title,optional" validate:"omitempty,max=200"`
	Content string `json:"content,optional" validate:"omitempty,max=10000"`
	Status  string `json:"status,optional" validate:"omitempty,oneof=draft completed failed"`
}

type UpdateStudentReq struct {
	Id             int64          `json:"id" validate:"required,gt=0"`
	Name           string         `json:"name,optional" validate:"omitempty,min=2,max=50"`
	Education      string         `json:"education,optional" validate:"omitempty,oneof=high_school bachelor master phd"`
	Major          string         `json:"major,optional" validate:"omitempty,min=2,max=100"`
	GraduationYear int            `json:"graduationYear,optional" validate:"omitempty,min=2020,max=2030"`
	Skills         []StudentSkill `json:"skills,optional"`
	Certificates   []StudentCert  `json:"certificates,optional"`
	SoftSkills     SoftSkills     `json:"softSkills,optional"`
	Internship     []Internship   `json:"internship,optional"`
	Projects       []Project      `json:"projects,optional"`
}

type UpdateUserReq struct {

	Email string `json:"email,optional" validate:"omitempty,email"`

	Phone string `json:"phone,optional" validate:"omitempty,len=11"`

}



type UserInfo struct {

	Id        int64  `json:"id"`

	Username  string `json:"username"`

	Email     string `json:"email"`

	Phone     string `json:"phone"`

	Role      string `json:"role"`

	CreatedAt int64 `json:"createdAt"`

}



type UserResp struct {

	Code int       `json:"code"`

	Msg  string    `json:"msg"`

	Data *UserInfo `json:"data,optional"`

}



type StartInterviewReq struct {

	Mode string `json:"mode,optional" validate:"omitempty,oneof=practice assessment"`

}



type InterviewResp struct {

	Code int              `json:"code"`

	Msg  string           `json:"msg"`

	Data *InterviewSession `json:"data,optional"`

}



type InterviewSession struct {

	Id        int64  `json:"id"`

	Mode      string `json:"mode"`

	Status    string `json:"status"`

	CreatedAt int64  `json:"createdAt"`

}



type InterviewChatStreamReq struct {

	Message string `json:"message" validate:"required,min=1,max=500"`

}



type InterviewHistoryResp struct {

	Id        int64   `json:"id"`

	Mode      string  `json:"mode"`

	Score     float64 `json:"score"`

	Status    string  `json:"status"`

	CreatedAt int64   `json:"createdAt"`

}



type InterviewHistoryListResp struct {

	Code int                     `json:"code"`

	Msg  string                  `json:"msg"`

	Data *InterviewHistoryResult `json:"data,optional"`

}



type InterviewHistoryResult struct {

	Total int64                   `json:"total"`

	List  []InterviewHistoryResp  `json:"list"`

}
