// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateStudentReq struct {
	Name           string         `json:"name,optional,validate:"omitempty,min=2,max=50"`
	Education      string         `json:"education,optional,validate:"omitempty,oneof=high_school bachelor master phd"`
	Major          string         `json:"major,optional,validate:"omitempty,min=2,max=100"`
	GraduationYear int            `json:"graduationYear,optional,validate:"omitempty,min=2020,max=2030"`
	Skills         []StudentSkill `json:"skills,optional"`
	Certificates   []StudentCert  `json:"certificates,optional"`
	SoftSkills     SoftSkills     `json:"softSkills,optional"`
	Internship     []Internship   `json:"internship,optional"`
	Projects       []Project      `json:"projects,optional"`
}

type GenerateProfileReq struct {
	ResumeContent string `json:"resumeContent,validate:"required,min=10"`
}

type Internship struct {
	Company     string `json:"company"`
	Position    string `json:"position"`
	Duration    int    `json:"duration"`
	Description string `json:"description"`
}

type Project struct {
	Name         string   `json:"name"`
	Role         string   `json:"role"`
	Description  string   `json:"description"`
	Technologies []string `json:"technologies"`
}

type ResumeUploadReq struct {
	FileContent string `json:"fileContent,validate:"required"`
	FileName    string `json:"fileName,validate:"required,min=1,max=255"`
}

type SoftSkills struct {
	Innovation    int `json:"innovation"`
	Learning      int `json:"learning"`
	Pressure      int `json:"pressure"`
	Communication int `json:"communication"`
	Teamwork      int `json:"teamwork"`
}

type StudentCert struct {
	Name  string `json:"name"`
	Level string `json:"level"`
	Year  int    `json:"year"`
}

type StudentListReq struct {
	Page      int    `form:"page,default=1"`
	PageSize  int    `form:"pageSize,default=10"`
	Major     string `form:"major,optional"`
	Education string `form:"education,optional"`
}

type StudentListResp struct {
	Total int64            `json:"total"`
	List  []StudentProfile `json:"list"`
}

type StudentListResultResp struct {
	Code int              `json:"code"`
	Msg  string           `json:"msg"`
	Data *StudentListResp `json:"data,optional"`
}

type StudentProfile struct {
	Id              int64          `json:"id"`
	UserId          int64          `json:"userId"`
	Name            string         `json:"name"`
	Education       string         `json:"education"`
	Major           string         `json:"major"`
	GraduationYear  int            `json:"graduationYear"`
	Skills          []StudentSkill `json:"skills"`
	Certificates    []StudentCert  `json:"certificates"`
	SoftSkills      SoftSkills     `json:"softSkills"`
	Internship      []Internship   `json:"internship"`
	Projects        []Project      `json:"projects"`
	Completeness    float64        `json:"completeness"`
	Competitiveness float64        `json:"competitiveness"`
	Suggestions     []string       `json:"suggestions"`
	CreatedAt       int64          `json:"createdAt"`
	UpdatedAt       int64          `json:"updatedAt"`
}

type StudentResp struct {
	Code int             `json:"code"`
	Msg  string          `json:"msg"`
	Data *StudentProfile `json:"data,optional"`
}

type StudentSkill struct {
	Name  string `json:"name"`
	Level int    `json:"level"`
	Years int    `json:"years"`
}

type UpdateStudentReq struct {
	Id             int64          `json:"id,validate:"required,gt=0"`
	Name           string         `json:"name,optional,validate:"omitempty,min=2,max=50"`
	Education      string         `json:"education,optional,validate:"omitempty,oneof=high_school bachelor master phd"`
	Major          string         `json:"major,optional,validate:"omitempty,min=2,max=100"`
	GraduationYear int            `json:"graduationYear,optional,validate:"omitempty,min=2020,max=2030"`
	Skills         []StudentSkill `json:"skills,optional"`
	Certificates   []StudentCert  `json:"certificates,optional"`
	SoftSkills     SoftSkills     `json:"softSkills,optional"`
	Internship     []Internship   `json:"internship,optional"`
	Projects       []Project      `json:"projects,optional"`
}
