// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	interviewReportsFieldNames          = builder.RawFieldNames(&InterviewReports{})
	interviewReportsRows                = strings.Join(interviewReportsFieldNames, ",")
	interviewReportsRowsExpectAutoSet   = strings.Join(stringx.Remove(interviewReportsFieldNames, "`id`", "`created_at`", "`updated_at`"), ",")
	interviewReportsRowsWithPlaceHolder = strings.Join(stringx.Remove(interviewReportsFieldNames, "`id`", "`created_at`", "`updated_at`"), "=?,") + "=?"
)

type (
	interviewReportsModel interface {
		Insert(ctx context.Context, data *InterviewReports) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*InterviewReports, error)
		Update(ctx context.Context, data *InterviewReports) error
		Delete(ctx context.Context, id int64) error
	}

	defaultInterviewReportsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	InterviewReports struct {
		Id                    int64          `db:"id"`
		SessionId             int64          `db:"session_id"`
		UserId                int64          `db:"user_id"`
		OverallScore          float64        `db:"overall_score"`
		SkillScore            sql.NullFloat64 `db:"skill_score"`
		CommunicationScore    sql.NullFloat64 `db:"communication_score"`
		LogicScore            sql.NullFloat64 `db:"logic_score"`
		ConfidenceScore       sql.NullFloat64 `db:"confidence_score"`
		Strengths             sql.NullString `db:"strengths"`
		Weaknesses            sql.NullString `db:"weaknesses"`
		ImprovementSuggestions sql.NullString `db:"improvement_suggestions"`
		Summary               sql.NullString `db:"summary"`
		CreatedAt             int64          `db:"created_at"`
		UpdatedAt             int64          `db:"updated_at"`
	}
)

// newInterviewReportsModel returns a model for the database table.
func newInterviewReportsModel(conn sqlx.SqlConn) *defaultInterviewReportsModel {
	return &defaultInterviewReportsModel{
		conn:  conn,
		table: "`interview_reports`",
	}
}

// Insert inserts a new InterviewReports record
func (m *defaultInterviewReportsModel) Insert(ctx context.Context, data *InterviewReports) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, interviewReportsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SessionId, data.UserId, data.OverallScore, data.SkillScore, data.CommunicationScore, data.LogicScore, data.ConfidenceScore, data.Strengths, data.Weaknesses, data.ImprovementSuggestions, data.Summary, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

// FindOne finds a InterviewReports record by id
func (m *defaultInterviewReportsModel) FindOne(ctx context.Context, id int64) (*InterviewReports, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", interviewReportsRows, m.table)
	var resp InterviewReports
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// Update updates a InterviewReports record
func (m *defaultInterviewReportsModel) Update(ctx context.Context, data *InterviewReports) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, interviewReportsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.SessionId, data.UserId, data.OverallScore, data.SkillScore, data.CommunicationScore, data.LogicScore, data.ConfidenceScore, data.Strengths, data.Weaknesses, data.ImprovementSuggestions, data.Summary, data.UpdatedAt, data.Id)
	return err
}

// Delete deletes a InterviewReports record by id
func (m *defaultInterviewReportsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}