// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	interviewSessionsFieldNames          = builder.RawFieldNames(&InterviewSessions{})
	interviewSessionsRows                = strings.Join(interviewSessionsFieldNames, ",")
	interviewSessionsRowsExpectAutoSet   = strings.Join(stringx.Remove(interviewSessionsFieldNames, "`id`", "`created_at`", "`updated_at`"), ",")
	interviewSessionsRowsWithPlaceHolder = strings.Join(stringx.Remove(interviewSessionsFieldNames, "`id`", "`created_at`", "`updated_at`"), "=?,") + "=?"
)

type (
	interviewSessionsModel interface {
		Insert(ctx context.Context, data *InterviewSessions) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*InterviewSessions, error)
		Update(ctx context.Context, data *InterviewSessions) error
		Delete(ctx context.Context, id int64) error
	}

	defaultInterviewSessionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	InterviewSessions struct {
		Id              int64          `db:"id"`
		UserId          int64          `db:"user_id"`
		StudentId       sql.NullInt64  `db:"student_id"`
		Mode            string         `db:"mode"`
		Status          string         `db:"status"`
		TotalQuestions  int            `db:"total_questions"`
		CurrentQuestion int            `db:"current_question"`
		AverageScore    float64        `db:"average_score"`
		MaxScore        float64        `db:"max_score"`
		MinScore        float64        `db:"min_score"`
		DurationSeconds int            `db:"duration_seconds"`
		CreatedAt       int64          `db:"created_at"`
		UpdatedAt       int64          `db:"updated_at"`
		CompletedAt     sql.NullInt64  `db:"completed_at"`
	}
)

// newInterviewSessionsModel returns a model for the database table.
func newInterviewSessionsModel(conn sqlx.SqlConn) *defaultInterviewSessionsModel {
	return &defaultInterviewSessionsModel{
		conn:  conn,
		table: "`interview_sessions`",
	}
}

// Insert inserts a new InterviewSessions record
func (m *defaultInterviewSessionsModel) Insert(ctx context.Context, data *InterviewSessions) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, interviewSessionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.StudentId, data.Mode, data.Status, data.TotalQuestions, data.CurrentQuestion, data.AverageScore, data.MaxScore, data.MinScore, data.DurationSeconds, data.CreatedAt, data.UpdatedAt, data.CompletedAt)
	return ret, err
}

// FindOne finds a InterviewSessions record by id
func (m *defaultInterviewSessionsModel) FindOne(ctx context.Context, id int64) (*InterviewSessions, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", interviewSessionsRows, m.table)
	var resp InterviewSessions
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// Update updates a InterviewSessions record
func (m *defaultInterviewSessionsModel) Update(ctx context.Context, data *InterviewSessions) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, interviewSessionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.StudentId, data.Mode, data.Status, data.TotalQuestions, data.CurrentQuestion, data.AverageScore, data.MaxScore, data.MinScore, data.DurationSeconds, data.CompletedAt, data.UpdatedAt, data.Id)
	return err
}

// Delete deletes a InterviewSessions record by id
func (m *defaultInterviewSessionsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}