// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	student "career-api/internal/handler/student"
	"career-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Create student profile
				Method:  http.MethodPost,
				Path:    "/students",
				Handler: student.CreateStudentHandler(serverCtx),
			},
			{
				// Update student profile
				Method:  http.MethodPut,
				Path:    "/students",
				Handler: student.UpdateStudentHandler(serverCtx),
			},
			{
				// List student profiles
				Method:  http.MethodGet,
				Path:    "/students",
				Handler: student.ListStudentsHandler(serverCtx),
			},
			{
				// Get student profile by id
				Method:  http.MethodGet,
				Path:    "/students/:id",
				Handler: student.GetStudentHandler(serverCtx),
			},
			{
				// Delete student profile
				Method:  http.MethodDelete,
				Path:    "/students/:id",
				Handler: student.DeleteStudentHandler(serverCtx),
			},
			{
				// Generate student capability profile via AI
				Method:  http.MethodPost,
				Path:    "/students/generate",
				Handler: student.GenerateProfileHandler(serverCtx),
			},
			{
				// Get current student profile
				Method:  http.MethodGet,
				Path:    "/students/me",
				Handler: student.GetMyProfileHandler(serverCtx),
			},
			{
				// Upload resume and generate profile via AI
				Method:  http.MethodPost,
				Path:    "/students/resume",
				Handler: student.UploadResumeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
