// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"time"

	graph "career-api/internal/handler/graph"
	job "career-api/internal/handler/job"
	match "career-api/internal/handler/match"
	report "career-api/internal/handler/report"
	student "career-api/internal/handler/student"
	user "career-api/internal/handler/user"
	"career-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Health check
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Get all job paths (promotion + transfer)
				Method:  http.MethodGet,
				Path:    "/jobs/:id/all-paths",
				Handler: graph.GetAllPathsHandler(serverCtx),
			},
			{
				// Get promotion path for a job
				Method:  http.MethodGet,
				Path:    "/jobs/:id/promotion-path",
				Handler: graph.GetPromotionPathHandler(serverCtx),
			},
			{
				// Get related jobs
				Method:  http.MethodGet,
				Path:    "/jobs/:id/related",
				Handler: graph.GetRelatedJobsHandler(serverCtx),
			},
			{
				// Get transfer paths for a job
				Method:  http.MethodGet,
				Path:    "/jobs/:id/transfer-paths",
				Handler: graph.GetTransferPathsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Create job profile
				Method:  http.MethodPost,
				Path:    "/jobs",
				Handler: job.CreateJobHandler(serverCtx),
			},
			{
				// Update job profile
				Method:  http.MethodPut,
				Path:    "/jobs",
				Handler: job.UpdateJobHandler(serverCtx),
			},
			{
				// List job profiles
				Method:  http.MethodGet,
				Path:    "/jobs",
				Handler: job.ListJobsHandler(serverCtx),
			},
			{
				// Get job profile by id
				Method:  http.MethodGet,
				Path:    "/jobs/:id",
				Handler: job.GetJobHandler(serverCtx),
			},
			{
				// Delete job profile
				Method:  http.MethodDelete,
				Path:    "/jobs/:id",
				Handler: job.DeleteJobHandler(serverCtx),
			},
			{
				// Generate job profile via AI
				Method:  http.MethodPost,
				Path:    "/jobs/generate",
				Handler: job.GenerateJobProfileHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Match student to single job
				Method:  http.MethodPost,
				Path:    "/match",
				Handler: match.MatchStudentJobHandler(serverCtx),
			},
			{
				// Get match score for a job
				Method:  http.MethodGet,
				Path:    "/match/:studentId/:jobId/score",
				Handler: match.GetMatchScoreHandler(serverCtx),
			},
			{
				// Get recommended jobs for student
				Method:  http.MethodGet,
				Path:    "/match/:studentId/recommend",
				Handler: match.GetRecommendedJobsHandler(serverCtx),
			},
			{
				// Match student to multiple jobs
				Method:  http.MethodPost,
				Path:    "/match/jobs",
				Handler: match.MatchStudentJobsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(30000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Update report
				Method:  http.MethodPut,
				Path:    "/reports",
				Handler: report.UpdateReportHandler(serverCtx),
			},
			{
				// List reports
				Method:  http.MethodGet,
				Path:    "/reports",
				Handler: report.ListReportsHandler(serverCtx),
			},
			{
				// Get report by id
				Method:  http.MethodGet,
				Path:    "/reports/:id",
				Handler: report.GetReportHandler(serverCtx),
			},
			{
				// Delete report
				Method:  http.MethodDelete,
				Path:    "/reports/:id",
				Handler: report.DeleteReportHandler(serverCtx),
			},
			{
				// Check report completeness
				Method:  http.MethodGet,
				Path:    "/reports/:id/completeness",
				Handler: report.CheckReportCompletenessHandler(serverCtx),
			},
			{
				// Export report
				Method:  http.MethodPost,
				Path:    "/reports/export",
				Handler: report.ExportReportHandler(serverCtx),
			},
			{
				// Generate career development report
				Method:  http.MethodPost,
				Path:    "/reports/generate",
				Handler: report.GenerateReportHandler(serverCtx),
			},
			{
				// Generate career report via SSE stream
				Method:  http.MethodGet,
				Path:    "/reports/generate-stream",
				Handler: report.GenerateReportStreamHandler(serverCtx),
			},
			{
				// Get my reports
				Method:  http.MethodGet,
				Path:    "/reports/me",
				Handler: report.GetMyReportsHandler(serverCtx),
			},
			{
				// Polish and optimize report
				Method:  http.MethodPost,
				Path:    "/reports/polish",
				Handler: report.PolishReportHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(60000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Create student profile
				Method:  http.MethodPost,
				Path:    "/students",
				Handler: student.CreateStudentHandler(serverCtx),
			},
			{
				// Update student profile
				Method:  http.MethodPut,
				Path:    "/students",
				Handler: student.UpdateStudentHandler(serverCtx),
			},
			{
				// List student profiles
				Method:  http.MethodGet,
				Path:    "/students",
				Handler: student.ListStudentsHandler(serverCtx),
			},
			{
				// Get student profile by id
				Method:  http.MethodGet,
				Path:    "/students/:id",
				Handler: student.GetStudentHandler(serverCtx),
			},
			{
				// Delete student profile
				Method:  http.MethodDelete,
				Path:    "/students/:id",
				Handler: student.DeleteStudentHandler(serverCtx),
			},
			{
				// Generate student capability profile via AI
				Method:  http.MethodPost,
				Path:    "/students/generate",
				Handler: student.GenerateProfileHandler(serverCtx),
			},
			{
				// Get current student profile
				Method:  http.MethodGet,
				Path:    "/students/me",
				Handler: student.GetMyProfileHandler(serverCtx),
			},
			{
				// Upload resume and generate profile via AI
				Method:  http.MethodPost,
				Path:    "/students/resume",
				Handler: student.UploadResumeHandler(serverCtx),
			},
			{
				// Get resume parse history
				Method:  http.MethodGet,
				Path:    "/students/resume/history",
				Handler: student.GetResumeHistoryHandler(serverCtx),
			},
			{
				// Get resume parse history detail
				Method:  http.MethodGet,
				Path:    "/students/resume/history/:id",
				Handler: student.GetResumeHistoryDetailHandler(serverCtx),
			},
			{
				// Delete resume parse history record
				Method:  http.MethodDelete,
				Path:    "/students/resume/history/:id",
				Handler: student.DeleteResumeHistoryHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Get user info
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
			{
				// Update user info
				Method:  http.MethodPut,
				Path:    "/user/info",
				Handler: user.UpdateUserInfoHandler(serverCtx),
			},
			{
				// User login
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// User registration
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
