// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	careerReportsFieldNames          = builder.RawFieldNames(&CareerReports{})
	careerReportsRows                = strings.Join(careerReportsFieldNames, ",")
	careerReportsRowsExpectAutoSet   = strings.Join(stringx.Remove(careerReportsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	careerReportsRowsWithPlaceHolder = strings.Join(stringx.Remove(careerReportsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	careerReportsModel interface {
		Insert(ctx context.Context, data *CareerReports) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CareerReports, error)
		Update(ctx context.Context, data *CareerReports) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCareerReportsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CareerReports struct {
		Id            int64          `db:"id"`
		StudentId     int64          `db:"student_id"`
		TargetJobId   sql.NullInt64  `db:"target_job_id"`
		Title         sql.NullString `db:"title"`
		Content       sql.NullString `db:"content"`
		Overview      sql.NullString `db:"overview"`
		MatchAnalysis sql.NullString `db:"match_analysis"`
		CareerPath    sql.NullString `db:"career_path"`
		ActionPlan    sql.NullString `db:"action_plan"`
		Status        string         `db:"status"`
		CreatedAt     int64          `db:"created_at"`
		UpdatedAt     int64          `db:"updated_at"`
	}
)

func newCareerReportsModel(conn sqlx.SqlConn) *defaultCareerReportsModel {
	return &defaultCareerReportsModel{
		conn:  conn,
		table: "`career_reports`",
	}
}

func (m *defaultCareerReportsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCareerReportsModel) FindOne(ctx context.Context, id int64) (*CareerReports, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", careerReportsRows, m.table)
	var resp CareerReports
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCareerReportsModel) Insert(ctx context.Context, data *CareerReports) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, careerReportsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.StudentId, data.TargetJobId, data.Title, data.Content, data.Overview, data.MatchAnalysis, data.CareerPath, data.ActionPlan, data.Status)
	return ret, err
}

func (m *defaultCareerReportsModel) Update(ctx context.Context, data *CareerReports) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, careerReportsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.StudentId, data.TargetJobId, data.Title, data.Content, data.Overview, data.MatchAnalysis, data.CareerPath, data.ActionPlan, data.Status, data.Id)
	return err
}

func (m *defaultCareerReportsModel) tableName() string {
	return m.table
}
