// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	interviewMessagesFieldNames          = builder.RawFieldNames(&InterviewMessages{})
	interviewMessagesRows                = strings.Join(interviewMessagesFieldNames, ",")
	interviewMessagesRowsExpectAutoSet   = strings.Join(stringx.Remove(interviewMessagesFieldNames, "`id`", "`created_at`"), ",")
	interviewMessagesRowsWithPlaceHolder = strings.Join(stringx.Remove(interviewMessagesFieldNames, "`id`", "`created_at`"), "=?,") + "=?"
)

type (
	interviewMessagesModel interface {
		Insert(ctx context.Context, data *InterviewMessages) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*InterviewMessages, error)
		Update(ctx context.Context, data *InterviewMessages) error
		Delete(ctx context.Context, id int64) error
	}

	defaultInterviewMessagesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	InterviewMessages struct {
		Id            int64          `db:"id"`
		SessionId     int64          `db:"session_id"`
		Role          string         `db:"role"`
		Content       string         `db:"content"`
		QuestionType  sql.NullString `db:"question_type"`
		Score         sql.NullFloat64 `db:"score"`
		Feedback      sql.NullString `db:"feedback"`
		CreatedAt     int64          `db:"created_at"`
	}
)

// newInterviewMessagesModel returns a model for the database table.
func newInterviewMessagesModel(conn sqlx.SqlConn) *defaultInterviewMessagesModel {
	return &defaultInterviewMessagesModel{
		conn:  conn,
		table: "`interview_messages`",
	}
}

// Insert inserts a new InterviewMessages record
func (m *defaultInterviewMessagesModel) Insert(ctx context.Context, data *InterviewMessages) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, interviewMessagesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.SessionId, data.Role, data.Content, data.QuestionType, data.Score, data.Feedback, data.CreatedAt)
	return ret, err
}

// FindOne finds a InterviewMessages record by id
func (m *defaultInterviewMessagesModel) FindOne(ctx context.Context, id int64) (*InterviewMessages, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", interviewMessagesRows, m.table)
	var resp InterviewMessages
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// Update updates a InterviewMessages record
func (m *defaultInterviewMessagesModel) Update(ctx context.Context, data *InterviewMessages) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, interviewMessagesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.SessionId, data.Role, data.Content, data.QuestionType, data.Score, data.Feedback, data.Id)
	return err
}

// Delete deletes a InterviewMessages record by id
func (m *defaultInterviewMessagesModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}