// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	jobPromotionPathsFieldNames          = builder.RawFieldNames(&JobPromotionPaths{})
	jobPromotionPathsRows                = strings.Join(jobPromotionPathsFieldNames, ",")
	jobPromotionPathsRowsExpectAutoSet   = strings.Join(stringx.Remove(jobPromotionPathsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	jobPromotionPathsRowsWithPlaceHolder = strings.Join(stringx.Remove(jobPromotionPathsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	jobPromotionPathsModel interface {
		Insert(ctx context.Context, data *JobPromotionPaths) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*JobPromotionPaths, error)
		Update(ctx context.Context, data *JobPromotionPaths) error
		Delete(ctx context.Context, id int64) error
	}

	defaultJobPromotionPathsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	JobPromotionPaths struct {
		Id             int64           `db:"id"`
		FromJobId      int64           `db:"from_job_id"`
		ToJobId        int64           `db:"to_job_id"`
		MatchScore     sql.NullFloat64 `db:"match_score"`
		TransferSkills sql.NullString  `db:"transfer_skills"`
		LearningPath   sql.NullString  `db:"learning_path"`
	}
)

func newJobPromotionPathsModel(conn sqlx.SqlConn) *defaultJobPromotionPathsModel {
	return &defaultJobPromotionPathsModel{
		conn:  conn,
		table: "`job_promotion_paths`",
	}
}

func (m *defaultJobPromotionPathsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultJobPromotionPathsModel) FindOne(ctx context.Context, id int64) (*JobPromotionPaths, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", jobPromotionPathsRows, m.table)
	var resp JobPromotionPaths
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultJobPromotionPathsModel) Insert(ctx context.Context, data *JobPromotionPaths) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, jobPromotionPathsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.FromJobId, data.ToJobId, data.MatchScore, data.TransferSkills, data.LearningPath)
	return ret, err
}

func (m *defaultJobPromotionPathsModel) Update(ctx context.Context, data *JobPromotionPaths) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, jobPromotionPathsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.FromJobId, data.ToJobId, data.MatchScore, data.TransferSkills, data.LearningPath, data.Id)
	return err
}

func (m *defaultJobPromotionPathsModel) tableName() string {
	return m.table
}
