// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	jobsFieldNames          = builder.RawFieldNames(&Jobs{})
	jobsRows                = strings.Join(jobsFieldNames, ",")
	jobsRowsExpectAutoSet   = strings.Join(stringx.Remove(jobsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	jobsRowsWithPlaceHolder = strings.Join(stringx.Remove(jobsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	jobsModel interface {
		Insert(ctx context.Context, data *Jobs) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Jobs, error)
		Update(ctx context.Context, data *Jobs) error
		Delete(ctx context.Context, id int64) error
	}

	defaultJobsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Jobs struct {
		Id              int64          `db:"id"`
		Name            string         `db:"name"`
		Description     sql.NullString `db:"description"`
		Company         sql.NullString `db:"company"`
		Industry        sql.NullString `db:"industry"`
		Location        sql.NullString `db:"location"`
		SalaryRange     sql.NullString `db:"salary_range"`
		Skills          sql.NullString `db:"skills"`
		Certificates    sql.NullString `db:"certificates"`
		SoftSkills      sql.NullString `db:"soft_skills"`
		Requirements    sql.NullString `db:"requirements"`
		GrowthPotential sql.NullString `db:"growth_potential"`
		CreatedAt       int64          `db:"created_at"`
		UpdatedAt       int64          `db:"updated_at"`
	}
)

func newJobsModel(conn sqlx.SqlConn) *defaultJobsModel {
	return &defaultJobsModel{
		conn:  conn,
		table: "`jobs`",
	}
}

func (m *defaultJobsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultJobsModel) FindOne(ctx context.Context, id int64) (*Jobs, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", jobsRows, m.table)
	var resp Jobs
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultJobsModel) Insert(ctx context.Context, data *Jobs) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, jobsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Description, data.Company, data.Industry, data.Location, data.SalaryRange, data.Skills, data.Certificates, data.SoftSkills, data.Requirements, data.GrowthPotential)
	return ret, err
}

func (m *defaultJobsModel) Update(ctx context.Context, data *Jobs) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, jobsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Description, data.Company, data.Industry, data.Location, data.SalaryRange, data.Skills, data.Certificates, data.SoftSkills, data.Requirements, data.GrowthPotential, data.Id)
	return err
}

func (m *defaultJobsModel) tableName() string {
	return m.table
}
