// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	matchRecordsFieldNames          = builder.RawFieldNames(&MatchRecords{})
	matchRecordsRows                = strings.Join(matchRecordsFieldNames, ",")
	matchRecordsRowsExpectAutoSet   = strings.Join(stringx.Remove(matchRecordsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	matchRecordsRowsWithPlaceHolder = strings.Join(stringx.Remove(matchRecordsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	matchRecordsModel interface {
		Insert(ctx context.Context, data *MatchRecords) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MatchRecords, error)
		Update(ctx context.Context, data *MatchRecords) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMatchRecordsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MatchRecords struct {
		Id              int64           `db:"id"`
		StudentId       int64           `db:"student_id"`
		JobId           int64           `db:"job_id"`
		OverallScore    sql.NullFloat64 `db:"overall_score"`
		SkillsMatch     sql.NullFloat64 `db:"skills_match"`
		CertsMatch      sql.NullFloat64 `db:"certs_match"`
		SoftSkillsMatch sql.NullFloat64 `db:"soft_skills_match"`
		ExperienceMatch sql.NullFloat64 `db:"experience_match"`
		GapAnalysis     sql.NullString  `db:"gap_analysis"`
		CreatedAt       int64           `db:"created_at"`
	}
)

func newMatchRecordsModel(conn sqlx.SqlConn) *defaultMatchRecordsModel {
	return &defaultMatchRecordsModel{
		conn:  conn,
		table: "`match_records`",
	}
}

func (m *defaultMatchRecordsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMatchRecordsModel) FindOne(ctx context.Context, id int64) (*MatchRecords, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", matchRecordsRows, m.table)
	var resp MatchRecords
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMatchRecordsModel) Insert(ctx context.Context, data *MatchRecords) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, matchRecordsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.StudentId, data.JobId, data.OverallScore, data.SkillsMatch, data.CertsMatch, data.SoftSkillsMatch, data.ExperienceMatch, data.GapAnalysis)
	return ret, err
}

func (m *defaultMatchRecordsModel) Update(ctx context.Context, data *MatchRecords) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, matchRecordsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.StudentId, data.JobId, data.OverallScore, data.SkillsMatch, data.CertsMatch, data.SoftSkillsMatch, data.ExperienceMatch, data.GapAnalysis, data.Id)
	return err
}

func (m *defaultMatchRecordsModel) tableName() string {
	return m.table
}
