// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	studentsFieldNames          = builder.RawFieldNames(&Students{})
	studentsRows                = strings.Join(studentsFieldNames, ",")
	studentsRowsExpectAutoSet   = strings.Join(stringx.Remove(studentsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	studentsRowsWithPlaceHolder = strings.Join(stringx.Remove(studentsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	studentsModel interface {
		Insert(ctx context.Context, data *Students) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Students, error)
		Update(ctx context.Context, data *Students) error
		Delete(ctx context.Context, id int64) error
	}

	defaultStudentsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Students struct {
		Id                   int64          `db:"id"`
		UserId               int64          `db:"user_id"`
		Name                 string         `db:"name"`
		Education            sql.NullString `db:"education"`
		Major                sql.NullString `db:"major"`
		GraduationYear       sql.NullInt64  `db:"graduation_year"`
		Skills               sql.NullString `db:"skills"`
		Certificates         sql.NullString `db:"certificates"`
		SoftSkills           sql.NullString `db:"soft_skills"`
		Internship           sql.NullString `db:"internship"`
		Projects             sql.NullString `db:"projects"`
		CompletenessScore    float64        `db:"completeness_score"`
		CompetitivenessScore float64        `db:"competitiveness_score"`
		ResumeUrl            sql.NullString `db:"resume_url"`
		Suggestions          sql.NullString `db:"suggestions"`
		ResumeContent        sql.NullString `db:"resume_content"`
		CreatedAt            int64          `db:"created_at"`
		UpdatedAt            int64          `db:"updated_at"`
	}
)

func newStudentsModel(conn sqlx.SqlConn) *defaultStudentsModel {
	return &defaultStudentsModel{
		conn:  conn,
		table: "`students`",
	}
}

func (m *defaultStudentsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultStudentsModel) FindOne(ctx context.Context, id int64) (*Students, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", studentsRows, m.table)
	var resp Students
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStudentsModel) Insert(ctx context.Context, data *Students) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, studentsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Name, data.Education, data.Major, data.GraduationYear, data.Skills, data.Certificates, data.SoftSkills, data.Internship, data.Projects, data.CompletenessScore, data.CompetitivenessScore, data.ResumeUrl, data.Suggestions, data.ResumeContent)
	return ret, err
}

func (m *defaultStudentsModel) Update(ctx context.Context, data *Students) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, studentsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Name, data.Education, data.Major, data.GraduationYear, data.Skills, data.Certificates, data.SoftSkills, data.Internship, data.Projects, data.CompletenessScore, data.CompetitivenessScore, data.ResumeUrl, data.Suggestions, data.ResumeContent, data.Id)
	return err
}

func (m *defaultStudentsModel) tableName() string {
	return m.table
}
